modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"  # Add your license here# Accept 47 or newer, which covers 47.4.10

[[mods]]
modId = "homesweethome"
version = "1.0.0"
displayName = "Home Sweet Home"
description = "A new way to freshen up your home!"
authors = "Maiko Mid"

[[dependencies.homesweethome]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.homesweethome]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
